DMS.Web/Controllers/TreeSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DMS.Model;
using DMS.Service;
using System.Data;
using Newtonsoft.Json;
using Outlook = Microsoft.Office.Interop.Outlook;
using System.Net;
using System.Net.Mail;
using GleamTech.DocumentUltimate.AspNet.UI;
using GleamTech.Collections;
using GleamTech.DocumentUltimate;
using GleamTech.Data;
using DMS.Web.Filters;

namespace DMS.Web.Controllers
{
    [UserAuntheication]
    public class TreeSearchController : Controller
    {
        SetDocAttributes_Model deptsModel1 = new SetDocAttributes_Model();
        SetDocAttributes_Model depts1;
        SetDocAttributes_Service ServiceObj1 = new SetDocAttributes_Service();
        ViewDocument_Services ServiceObj2 = new ViewDocument_Services();
        PhysicalArchival_Model modelObj = new PhysicalArchival_Model();
        Search_Service ServiceObj = new Search_Service();
    
        ViewDocument_Services ObjService = new ViewDocument_Services();
        log4net.ILog logger = log4net.LogManager.GetLogger(typeof(TreeSearchController));  //Declaring Log4Net 
        // GET: Hierarchy
        public ActionResult Index()
        {
            TreeSearch_services context = new TreeSearch_services();
            try
            {//GetTreeData
                /*  var plist = context.HierarchyDetails.Where(p => p.PerentId == null).Select(a => new
                  {
                      a.Id,
                      a.HierarchyName
                  }).ToList();*/
                ViewBag.plist = context.GetTreeData();
            }
            catch (Exception ex)
            {
                logger.Error(ex.ToString());
            }
           // GetHierarchy();
            return View();
        }

        public JsonResult GetHierarchy()
        {
            List<HierarchyDetail> hdList;
            List<HierarchyViewModel> records;
            TreeSearch_services context = new TreeSearch_services();
            //try
            // {
            hdList = context.GetTreeData().ToList();

            records = hdList.Where(l => l.PerentId == 0)
                .Select(l => new HierarchyViewModel
                {
                    Id = l.Id,
                    text = l.HierarchyName,
                    perentId = l.PerentId,
                    children = GetChildren(hdList, l.Id)
                    //children = GetChildren(hdList, l.PerentId)
                }).ToList();
            // }
            //catch (Exception ex)
            //{
            //    logger.Error(ex.ToString());
            //}

            return this.Json(records, JsonRequestBehavior.AllowGet);
            // return View();
        }

        private List<HierarchyViewModel> GetChildren(List<HierarchyDetail> hdList, Int64 parentId)
        {
            return hdList.Where(l => l.PerentId == parentId)
                .Select(l => new HierarchyViewModel
                {
                    Id = l.Id,
                    text = l.HierarchyName,
                    perentId = l.PerentId,
                    children = GetChildren(hdList, l.Id)
                }).ToList();
        }

        [HttpPost]
        public ActionResult AttributeDataPartial(string data)
        {
            //string Data1 = "";
            TreeSearch_services objservice = new TreeSearch_services();
            //List<DMS.Model.Attribute> deptsModel = new List<DMS.Model.Attribute>();
            TreeSearch_Model deptsModel = new TreeSearch_Model();
            Int32 _empid = Convert.ToInt32(Session["Emp_Id"].ToString());
            DataSet ds = new DataSet();
            DataTable dt = new DataTable();
            try
            {
                ds = objservice.GetAttributes(data, _empid);
                dt = ds.Tables[0];
                //Data1 = JsonConvert.SerializeObject(dt);
                // deptsModel = objservice.GetAttributes(data, _empid);
                string Count = Convert.ToString(dt.Rows.Count);
                int Checkrcd = Convert.ToInt32(dt.Rows[0][0].ToString());
                ViewBag.AttributeCount = Convert.ToInt32(Count);
                int ctlval = 0;
                string type;
                int LovId;
                DataTable dt1 = new DataTable();
                if (Checkrcd == 0)
                {
                    //show the alert message..
                }
                else
                {
                    foreach (DataRow dr in dt.Rows)
                    {
                        TreeSearch_Model depts = new TreeSearch_Model();
                        depts.Atr_Name = dr["Atr_Name"].ToString();
                        depts.attrctlname = dr["Atr_Name"].ToString() + ctlval.ToString();
                        depts.Dname_Name = dr["Dname_Name"].ToString();
                        depts.Dgroup_Name = dr["Dgroup_Name"].ToString();
                        depts.Dgroup_Id = Convert.ToInt64(dr["Dgroup_Id"].ToString());
                        depts.Dname_Id = Convert.ToInt64(dr["Dname_Id"].ToString());
                        type = dr["Atr_Type"].ToString();
                        if (type == "Lov Name")
                        {
                            LovId = Convert.ToInt32(dr["Lov_Id"].ToString());
                            dt1 = ServiceObj.getmasterval(LovId);

                            List<SelectListItem> item8 = new List<SelectListItem>();
                            foreach (DataRow dr1 in dt1.Rows)
                            {
                                item8.Add(new SelectListItem
                                {
                                    Text = dr1["Lovexl_Name"].ToString(),
                                    Value = dr1["Lovexl_Name"].ToString()
                                });
                            }
                            ViewBag.Lovexl_Name = item8;
                            depts.LovName = item8;
                        }
                        depts.Atr_Type = dr["Atr_Type"].ToString();
                        List<SelectListItem> operat = new List<SelectListItem>();
                        operat.Add(new SelectListItem
                        {
                            Text = "AND",
                            Value = "AND"
                        });
                        operat.Add(new SelectListItem
                        {
                            Text = "OR",
                            Value = "OR"
                        });
                        depts.operators = operat;

                        List<SelectListItem> cond = new List<SelectListItem>();
                        cond.Add(new SelectListItem
                        {
                            Text = "Contains",
                            Value = "Contains"
                        });
                        cond.Add(new SelectListItem
                        {
                            Text = "StartWith",
                            Value = "StartWith"
                        });
                        cond.Add(new SelectListItem
                        {
                            Text = "EndWith",
                            Value = "EndWith"
                        });
                        cond.Add(new SelectListItem
                        {
                            Text = "Equal",
                            Value = "Equal"
                        });
                        depts.Conditions = cond;

                        deptsModel.dept.Add(depts);
                        ctlval++;
                    }
                }


            }
            catch (Exception ex)
            {
                logger.Error(ex.ToString());
            }
            return PartialView(deptsModel);
        }

        public ActionResult testpartial(int obj)
        {
            return PartialView(obj);
        }

        public ActionResult AttributeDataPartial(TreeSearch_Model obj)
        {

            return PartialView(obj);
        }

        public ActionResult GetDocuments(string Attributetypes1, string atrname1, string Docgroupid1, string Docnameid1, string Dyntextvalues1, string Conditions1, string operators1)
        {
            DataTable dt = new DataTable();
            DataTable dt1 = new DataTable();
            DataSet ds = new DataSet();
            TreeSearch_services objservice = new TreeSearch_services();
            Int32 _empid = Convert.ToInt32(Session["Emp_Id"].ToString());
            ds = objservice.GetDocuments(Attributetypes1, atrname1, Docgroupid1, Docnameid1, _empid, Dyntextvalues1, Conditions1, operators1);
            if (ds.Tables.Count > 0)
            {
                // var UniqueRows = ds.Tables[0].AsEnumerable().Distinct(DataRowComparer.Default);
                //  dt = UniqueRows.CopyToDataTable();
                dt = ds.Tables[0];
                if (ds.Tables.Count > 1)
                {
                    dt1 = ds.Tables[1];
                }
                else
                {
                    dt1 = ds.Tables[0];
                }
            }
            string Data1 = "", Data2 = "";
            Data1 = JsonConvert.SerializeObject(dt);
            Data2 = JsonConvert.SerializeObject(dt1);
            return Json(new { Data1, Data2 }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult showdocuments(int? viewid, string mode)
        {
            string filepath = "";
            try
            {
                filepath = ObjService.SingleFileDownload(viewid, mode);
                ViewBag.FilePath = filepath;
                return PartialView("DocpartialviewForTreeSearch", ViewBag.FilePath);
            }
            catch (Exception ex)
            {
                logger.Error(ex.ToString());
                return PartialView("DocpartialviewForTreeSearch");
            }
        }

        public ActionResult Showmailpartialview()
        {
            try
            {

DMS.Web/Views/TreeSearch/AttributeDataPartial - old.cshtml
@using Kendo.Mvc.UI;
@model DMS.Model.TreeSearch_Model

@{
    int i = 0;
    bool newrow = true;
    int colcnt = 0;
}
<div class="row">
    <table>

        @foreach (var category in Model.dept)
        {
            //if ( colcnt == 0)
            //{
                newrow = true;
                @*colcnt = 0;
                @Html.Raw("<tr style='height:30px;'>")
            }
            else
            {
                newrow = false;
            }*@
            if (newrow == true)
            {
                 @Html.Raw("<tr style='height:30px;'>")
                <td width="15px">@Html.Hidden("Attribtype" + i, @category.Atr_Type)</td>
                <td width="15px">@Html.Hidden("Attribname" + i, @category.Atr_Name)</td>
                <td width="15px">@Html.Hidden("Docgroupid" + i, @category.Dgroup_Id)</td>
                <td width="15px">@Html.Hidden("Docnameid" + i, @category.Dname_Id)</td>
                @*<td>
                    <label style="font-weight:normal;width:100px;">Attribute</label>
                </td>*@
                 <td>
                    @Html.TextArea("myTextArea", @category.Dgroup_Name + "/" + @category.Dname_Name + "/" + @category.Atr_Name, new { rows = 1, columns = 40, @readonly = "readonly", @class = "form-control", style = "height:30px;width:280px;" }) 
                </td>
                <td>
                    &nbsp;&nbsp;<label style="font-weight:bold;width:100px;">@category.Atr_Name </label>
                </td>
                @*<td width="30px"></td>*@
                if (category.Atr_Type == "Datetime")
                {
                    <td>
                        @Html.Editor("ctl" + i, null, new { htmlAttributes = new { @class = "form-control", style = "height:30px;width:200px;" }, })
                    </td>
                    
                    
                }
                if (category.Atr_Type == "Alpha Numeric")
                {
                    
                    <td style="width:120px">
                        @Html.TextBox("ctl" + i, null, new { @class = "form-control", style = "height:30px;width:200px;" })
                    </td>
                   
                }
                if (category.Atr_Type == "Numeric")
                {
                    
                    <td style="width:120px">
                        @Html.TextBox("ctl" + i, null, new { @class = "form-control", style = "height:30px;width:200px;", onkeypress = "return NumersOnly(event)" })
                    </td>
                    
                    
                }
                if (category.Atr_Type == "Amount")
                {
                    
                    <td style="width:120px">
                        @Html.TextBox("ctl" + i, null, new { @class = "form-control", style = "height:30px;width:200px;", onkeypress = "return isNumberKey(event)" })
                    </td>
                   
                    
                }
                if (category.Atr_Type == "Logical")
                {
                    <td style="width:120px">
                        @Html.RadioButton("ctl" + i, "Yes") Yes &nbsp;&nbsp;&nbsp;&nbsp;@Html.RadioButton("ctl" + i, "No") No
                    </td>

                }
                if (category.Atr_Type == "Lov Name")
                    {
                        <td>
                @*Html.DropDownList("ctl" + i, (IEnumerable<SelectListItem>)ViewBag.Lovexl_Name, "-Select-", new {  style = "height:25px;width:150px;font-weight: normal;" })*@
                @Html.DropDownList("ctl" + i, category.LovName, null, new { @class = "form-control", style = "height:30px;width:200px;font-weight: normal;" })
                        </td>
                    }
                    <td>
                        @Html.DropDownList("cont" + i, category.Conditions, null, new { @class = "form-control", style = "height:30px;width:200px;font-weight: normal;" })
                    </td>
                 <td>
                     @Html.DropDownList("ope" + i, category.operators, null, new { @class = "form-control", style = "height:30px;width:200px;font-weight: normal;" })
                </td>
            @Html.Raw("</tr>")
            }
            else
            {
                @Html.Raw("<tr style='height:30px;'>")
                <td width="15px">@Html.Hidden("Attribtype" + i, @category.Atr_Type)</td>
                <td width="15px">@Html.Hidden("Attribname" + i, @category.Atr_Name)</td>
                <td width="15px">@Html.Hidden("Docgroupid" + i, @category.Dgroup_Id)</td>
                <td width="15px">@Html.Hidden("Docnameid" + i, @category.Dname_Id)</td>
                <td>
                    <label style="font-weight:normal;width:100px;">Attribute</label>
                </td>
                 <td>
                    @Html.TextArea("myTextArea", @category.Dgroup_Name + "/" + @category.Dname_Name + "/" + @category.Atr_Name, new { rows = 1, columns = 40, @readonly = "readonly" })
                </td>
                <td>
                    <label style="font-weight:normal;width:100px;">@category.Atr_Name </label>
                </td>
                @*<td width="30px"></td>*@

                if (category.Atr_Type == "Datetime")
                {
                    <td>

                        @Html.Editor("ctl" + i, null, new { htmlAttributes = new { @class = "form-control", style = "height:30px;width:200px;" } })
                    </td>
                   
                    
                }
                if (category.Atr_Type == "Alpha Numeric")
                {
                    <td style="width:120px">
                        @Html.TextBox("ctl" + i, null, new { @class = "form-control", style = "height:30px;width:200px;" })
                    </td>
                    
                }
                if (category.Atr_Type == "Numeric")
                {
                    
                    <td style="width:120px">
                        @Html.TextBox("ctl" + i, null, new { @class = "form-control", style = "height:30px;width:200px;", onkeypress = "return NumersOnly(event)" })
                    </td>
                  
                }
                if (category.Atr_Type == "Amount")
                {
                    
                    <td style="width:120px">
                        @Html.TextBox("ctl" + i, null, new { @class = "form-control", style = "height:30px;width:200px;", onkeypress = "return isNumberKey(event)" })
                    </td>
                   
                }
                if (category.Atr_Type == "Logical")
                {
                    <td style="width:120px">
                        @Html.RadioButton("ctl" + i, "Yes") Yes &nbsp;&nbsp;&nbsp;&nbsp;@Html.RadioButton("ctl" + i, "No") No
                    </td>
                   
                }
                 if (category.Atr_Type == "Lov Name")
                 {
                     <td>
                         @*@Html.DropDownList("ctl" + i, (IEnumerable<SelectListItem>)ViewBag.Lovexl_Name, "-Select-", new { style = "height:25px;width:150px;font-weight: normal;" })*@
                         @Html.DropDownList("ctl" + i, category.LovName, null, new { @class = "orm-control", style = "height:30px;width:200px;font-weight: normal;" })
                     </td>
                    
                 }
                 <td>
                        @Html.DropDownList("cont" + i, category.Conditions, null, new { @class = "form-control", style = "height:30px;width:200px;font-weight: normal;" })
                    </td>
                 <td>
                     @Html.DropDownList("ope" + i, category.operators, null, new { @class = "form-control", style = "height:30px;width:500px;font-weight: normal;" })
                </td>
            @Html.Raw("</tr>")
            }
            if (colcnt == 0)
            {
                @Html.Raw("</tr>")
            }
            i++;
            colcnt++;
        }

    </table>
</div>
    <input type="hidden" id="ctlcount" value="@i" />

    <script type="text/javascript">
        var count = $('#ctlcount').val();
        var concatval;
        for (var i = 0; i < count; i++) {
            var Attributetypes = $('#Attribtype' + i).val();

            if (Attributetypes == "Datetime") {
                debugger;
                $('#ctl' + i).datepicker({
                    dateFormat: "dd-mm-yy",
                    changeMonth: true,
                    changeYear: true
                })
                //$('#ctl' + i).datepicker('setDate', 'today')
            }
            // var gettxtdesval = $('#ctl' + i).val();
        }
    </script>

DMS.Web/Views/TreeSearch/DocpartialviewForTreeSearch.cshtml
@using GleamTech.AspNet.Mvc
@using GleamTech.DocumentUltimate
@using GleamTech.DocumentUltimate.AspNet
@using GleamTech.DocumentUltimate.AspNet.UI
@using System.Web.UI.WebControls;
<style>
    .ui-dialog-titlebar-close {
        display: none;
    }

    label {
        font-size: medium;
        font-family: Cambria;
    }
</style>
<div class="row">
    <div class="col-md-12">
        <div class="box-body">
            <div class="row">
                <table>
                    <tr>
                        <td width="5%"></td>
                        <td>
                            @{
                                var documentViewer = new DocumentViewer
                        {
                            Width = 800,
                            Height = 650,
                            Document = ViewBag.FilePath
                        };
                            }
                            @this.RenderBody(documentViewer)
                            @this.RenderHead(documentViewer)
                        </td>
                    </tr>


                </table>
            </div>
        </div>

        <!-- /.box-body -->
        <div class="box-footer">
            <div class="row text-center mt20">
                <input type="button" value="Close" id="btn_cancel" onclick="return Close_Fordocument();" class="btn btn-orange fa fa-download" />
            </div>
        </div>
    </div>
</div>

<script>
    function Close_Fordocument() {
        debugger;
        objDialog12.dialog("close");
    }
</script>

DMS.Web/Views/TreeSearch/LinkInterfilingPartialView.cshtml
<style>
    .ui-dialog-titlebar-close {
        display: none;
    }
</style>

<div class="panel panel-primary">
    <div class="panel-heading">
        <table>
            <tr>
                <td><label style="font-weight:normal">Attributes</label></td>
                <td width="85%"></td>
                <td><button type="button" id="btnclose" style="color:black;font-weight:bold;" onclick="return Close_Forlinkedfile();">X</button></td>
            </tr>
        </table>
    </div>
</div>

<div style="width:100%">
    <table id="myTable" class="table order-list" style="width:100% ;font-weight:normal;"></table>

    @*<div class="row text-center mt20">
        <input type="button" value="Close" id="btn_cancel" onclick="return Close_Forlinkedfile();" class="btn btn-orange fa-align-center" />
    </div>*@
</div>

<script>
    function Close_Forlinkedfile() {
        debugger;
        objDialog10.dialog("close");
    }

    $(document).ready(function () {
        debugger;

        var group_type = $("#hdn_type").val();
        var group_gid = $("#hdn_gridgid").val();
        //$("#hdn_mode").val(mode);
        $.ajax({
            url: '@Url.Action("showdynamicattributes", "TreeSearch")',
            type: "POST",
            datatype: "json",
            async: false,
            data: { 'group_gid': group_gid, 'group_type': group_type },
            success: function (data) {
                debugger;
                var data2 = JSON.parse(data);
                for (i = 0; i < data2.length; i++) {
                    var newRow = $("<tr  width='100%'>");
                    var cols = "";
                    cols += '<td><label id="name' + i + '" style="font-weight:normal;font-size: 13px;height:3px;"></label></td> <td><label name="val' + i + '" id="val' + i + '" style="font-weight:normal;font-size: 13px;height:3px"></label></td>';
                    newRow.append(cols);
                    $("table.order-list").append(newRow);
                }
                for (i = 0; i < data2.length; i++) {
                    $("#name" + i).text(data2[i].Atr_Name);
                    $("#val" + i).text(data2[i].Attribdtl_Description);
                }
            },
            error: function () {
                $.alert({
                    title: 'DMS',
                    content: 'Failed to create..!',
                    type: 'blue',
                });
                return false;
            }
        });
    });
</script>

DMS.Web/Views/TreeSearch/OutlookPartialViewForSingleFile.cshtml
@model DMS.Model.ViewDocuments_Model

<style>
    .ui-dialog-titlebar-close {
        display: none;
    }

</style>

<div class="panel panel-primary">
    <div class="panel-heading">
        <table>
            <tr>
                <td><label style="font-weight:normal">Bulk Mail</label></td>
                <td width="85%"></td>
                <td><button type="button" id="btnclose" style="color:black;font-weight:bold;" onclick="return Close_Foroutlooklink();">X</button></td>
            </tr>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box-body">
            <div class="row">
                <table>

                    <tr>
                        <td style="width:25px"></td>
                        <td><label style="font-weight:normal;font-size:13px;font-family:sans-serif">To</label></td>
                        <td style="width:25px"></td>
                        <td>
                            @Html.TextBoxFor(m => m.MailTo, new { @class = "form-control", style = "height:25px;width:400px;font-weight: normal;font-size:13px;font-family:sans-serif", @placeholder = "Email Id" })
                        </td>
                    </tr>
                    <tr style="height:10px"></tr>
                    <tr>
                        <td style="width:25px"></td>
                        <td><label style="font-weight:normal;font-size:13px;font-family:sans-serif">Cc</label></td>
                        <td style="width:25px"></td>
                        <td>
                            @Html.TextBoxFor(m => m.MailCc, new { @class = "form-control", style = "height:25px;width:400px;font-weight: normal;font-size:13px;font-family:sans-serif", @placeholder = "Email Id" })
                        </td>
                    </tr>
                    <tr style="height:10px"></tr>
                    <tr>
                        <td style="width:25px"></td>
                        <td><label style="font-weight:normal;font-size:13px;font-family:sans-serif">Subject</label></td>
                        <td style="width:25px"></td>
                        <td>
                            @Html.TextBoxFor(m => m.MailSubject, new { @class = "form-control", style = "height:25px;width:400px;font-weight: normal;font-size:13px;font-family:sans-serif", @placeholder = "Subject" })
                            <span class="errormessage" id="erridmsg"></span>
                        </td>
                    </tr>
                    <tr style="height:10px"></tr>
                    <tr>
                        <td style="width:25px"></td>
                        <td><label style="font-weight:normal;font-size:13px;font-family:sans-serif">Attached File</label></td>
                        <td style="width:25px"></td>
                        <td>
                            <div class="input-group">
                                @Html.TextBoxFor(m => m.MailAttachement, new { @class = "form-control", style = "height:30px;width:330px;font-weight: normal;font-size:13px;font-family:sans-serif", @readonly = "true" })
                                &nbsp;&nbsp;&nbsp;&nbsp;<button type="button" class="btn btn-orange fa" id="btn_dwldfile" onclick="return downloadfile()">View</button>
                            </div>

                        </td>
                    </tr>
                    <tr style="height:10px"></tr>
                </table>
                <table>
                    <tr>
                        <td style="width:25px"></td>
                        <td>
                            @Html.TextArea("MailContent", null, new { @class = "form-control", style = "height:275px;width:515px;font-weight: normal;font-size:13px;font-family:sans-serif", @placeholder = "Body of the Content" })
                        </td>
                    </tr>
                </table>

            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <div class="row text-center mt20">
                <input type="button" value="Close" id="btn_cancel" onclick="return Close_Foroutlooklink();" class="btn btn-orange fa fa-download" />
                <input type="button" name="btnsubmit" value="Send" id="btn_sendmail" class="btn btn-orange fa fa-download" onclick="return SendMail();" />
            </div>

            <div class="row text-center mt20">
                <span class="errormessage"></span>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        debugger;
        var Indexed_gid = '@ViewBag.attachedid';//$("#hdn_attachid").val();
        var type = '@ViewBag.mode';//$("#hdn_linkorinterfile").val();
        // alert(Indexed_gid + '-' + type);
        $.ajax({
            url: '@Url.Action("Getgetfromidandattachfile", "TreeSearch")',
            type: "POST",
            datatype: "json",
            async: false,
            data: { 'Indexed_gid': Indexed_gid, 'type': type },
            success: function (data) {
                debugger;
                $("#MailFrom").val(data.Frommailaddress);
                $("#MailAttachement").val(data.Attachementfile);
                $("#hdn_filelocation").val(data.attachementlocation);
            },
            error: function () {
                alert("failed to create.")
                return false;
            }
        });
    });

    function Close_Foroutlooklink() {
        debugger;
        objDialog11.dialog("close");
    }

    function downloadfile() {
        debugger;

        @*$.ajax({
            url: '@Url.Action("Download", "ViewDocuments")',
            type: "POST",
            contentType: false,
            processData: false,
            data: fileData,
        }).done(function (data) {
            //get the file name for download
            if (data.attacheid != "") {
                //use window.location.href for redirect to download action for download the file
                window.location.href = "@Url.RouteUrl(new { Controller = "ViewDocuments", Action = "DownloadFile" })/?attacheid=" + data.attacheid;
            }
        });*@

        var downloadpath = $("#hdn_filelocation").val();
        $.ajax({
            url: '@Url.Action("Downloadmailfile", "TreeSearch")',
            type: "POST",
            datatype: "json",
            async: false,
            data: { 'downloadpath': downloadpath },
        }).done(function (data) {
            debugger;
            //get the file name for download
            if (data.downloadpath != "") {
                //use window.location.href for redirect to download action for download the file
                window.location.href = "@Url.RouteUrl(new { Controller = "TreeSearch", Action = "DownloadMailFile1" })/?downloadpath=" + data.downloadpath;
            }
        });
    }
    function SendMail() {
        debugger;
        // var mailfrom = $("#MailFrom").val();
        var mailto = $("#MailTo").val();
        var mailcc = $("#MailCc").val();
        if (mailto == "") {
            $.alert({
                title: 'DMS',
                content: 'Enter email address..!!',
                icon: 'fa fa-success',
                type: 'green',
            });
            return false;
        }
        var emailReg = /^([\w-\.]+@@([\w-]+\.)+[\w-]{2,4})?$/;
        if (!emailReg.test(mailto)) {
            $.alert({
                title: 'DMS',
                content: 'Enter valid email address..!!',
                icon: 'fa fa-success',
                type: 'red',
            });
            return false;
        }
        var subject = $("#MailSubject").val();
        var content = $("#MailContent").val();
        var filelocation = $("#hdn_filelocation").val();
        var mailtype = $("#hdn_mailtype").val();
        $.ajax({
            url: '@Url.Action("SendMail", "TreeSearch")',
            type: "POST",
            datatype: "json",
            async: false,
            data: { 'mailto': mailto, 'subject': subject, 'content': content, 'filelocation': filelocation, 'mailcc': mailcc, 'mailtype': mailtype },
            success: function (data) {
                debugger;
                if (data == "success") {
                    $.alert({
                        title: 'DMS',
                        content: 'Mail sent successfully!',
                        icon: 'fa fa-success',
                        type: 'blue',
                    });
                    setTimeout(function () {
                        //window.location.reload(1);
                        objDialog11.dialog("close");
                    }, 2500);
                }
                else {
                    $.alert({
                        title: 'DMS',
                        content: 'Mail could not be sent!!',
                        icon: 'fa fa-success',
                        type: 'orange',
                    });
                }
            },
        });
    }
</script>